### ISSUE TITLE
System.ComponentModel.Win32Exception: The program issued a command but the command length is incorrect

### ISSUE THREAD

**Issue by hongzhouchen-oceanwing** [lowleveldesign/process-governor#1]
Environment:
- Win 10 Version 1607 (OS Build 14393.105) 64bit

Call command: `procgov64.exe -m 20M -p 13088`

```
procgov64.exe -m 20M -p 13088

Unhandled Exception: System.ComponentModel.Win32Exception: The program issued a command but the command length is incorrect
   at LowLevelDesign.ProcessGovernor.AssignProcessToJobObject()
   at LowLevelDesign.ProcessGovernor.AttachToProcess(Int32 pid)
   at LowLevelDesign.Program.Main(String[] args)
```

**Comment by lowleveldesign** [comment]
@hongzhouchen-oceanwing is the process governer in the same bitness as the target process?

**Comment by hongzhouchen-oceanwing** [comment]
Thanks for your comment. It is built as x86 CPU.
