### ISSUE TITLE
hi,I have a problem:

### ISSUE THREAD

**Issue by zhuxi27** [lowleveldesign/process-governor#2]
use release version.
 like this:

D:\PROJ\mm2\MM\cmds>procgov.exe -maxmem 300M --pid 5980

Unhandled Exception: System.MissingMethodException: Method not found: 'Int32 System.Runtime.InteropServices.Marshal.SizeOf(!!0)'.
   at LowLevelDesign.ProcessGovernor.AssignProcessToJobObject()
   at LowLevelDesign.ProcessGovernor.AttachToProcess(Int32 pid)
   at LowLevelDesign.Program.Main(String[] args)

**Comment by lowleveldesign** [comment]
Hi, which version of .NET are you using? It seems that Marshal.SizeOf [requires .NET >= 4.5.1](https://msdn.microsoft.com/en-us/library/dn261466%28v=vs.110%29.aspx)

**Comment by lowleveldesign** [comment]
I'm closing this issue due to inactivity. Let me know if you still experience this error.
