### ISSUE TITLE
--maxmem Int Overflow

### ISSUE THREAD

**Issue by lib-dbr** [lowleveldesign/process-governor#5]
When setting --maxmem to greater than 3GB, the argument is either ignored in the registry key or set to limit to 2GB.

If I manually edit the registry to add a maxmem greater than 3GB, say 32GB, I receive an error on run 

Unhandled Exception: System.OverflowException: Value was either too large or too small for a UInt32.
   at System.Number.ParseUInt32(String value, NumberStyles options, NumberFormatInfo numfmt)
   at LowLevelDesign.Program.ParseMemoryString(String v)
   at LowLevelDesign.Program.<>c__DisplayClass0_0.<Main>b__0(String v)
   at NDesk.Options.Option.Invoke(OptionContext c)
   at NDesk.Options.OptionSet.ParseValue(String option, OptionContext c)
   at NDesk.Options.OptionSet.Parse(String argument, OptionContext c)
   at NDesk.Options.OptionSet.Parse(IEnumerable`1 arguments)
   at LowLevelDesign.Program.Main(String[] args)

Tested on 3 different machines. 
Windows Server 2012 and Server 2016
.Net 4.6 and .Net 4.7

Verified running the correct bitness.

**Comment by lowleveldesign** [comment]
Please check the [latest release](https://github.com/lowleveldesign/process-governor/releases/tag/2.2.18345). The overflow should no longer happen for 64-bit apps.
